package com.financeos.hub.core.backup

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

internal object BackupCrypto {
    private const val KEY_ALIAS  = "fos_backup_key"
    private const val PROVIDER   = "AndroidKeyStore"
    private const val ALGORITHM  = "AES/GCM/NoPadding"
    private const val IV_BYTES   = 12
    private const val TAG_BITS   = 128

    // File starts with this ASCII header to distinguish encrypted from legacy plaintext.
    private val HEADER = "FOSENC1:".toByteArray(Charsets.US_ASCII)

    fun encrypt(plaintext: ByteArray): ByteArray {
        val cipher = Cipher.getInstance(ALGORITHM)
        cipher.init(Cipher.ENCRYPT_MODE, getOrCreateKey())
        val iv         = cipher.iv          // 12 random bytes, generated by GCM
        val ciphertext = cipher.doFinal(plaintext)
        return HEADER + iv + ciphertext
    }

    /**
     * Decrypts data encrypted by [encrypt]. If the data does not start with [HEADER]
     * it is returned unchanged — backward-compat for plaintext backups written before
     * encryption was introduced.
     */
    fun decrypt(data: ByteArray): ByteArray {
        if (!data.startsWith(HEADER)) return data   // legacy plaintext backup
        val offset     = HEADER.size
        val iv         = data.copyOfRange(offset, offset + IV_BYTES)
        val ciphertext = data.copyOfRange(offset + IV_BYTES, data.size)
        val cipher = Cipher.getInstance(ALGORITHM)
        cipher.init(Cipher.DECRYPT_MODE, getOrCreateKey(), GCMParameterSpec(TAG_BITS, iv))
        return cipher.doFinal(ciphertext)
    }

    private fun ByteArray.startsWith(prefix: ByteArray): Boolean {
        if (size < prefix.size) return false
        return prefix.indices.all { this[it] == prefix[it] }
    }

    private fun getOrCreateKey(): SecretKey {
        val ks = KeyStore.getInstance(PROVIDER).apply { load(null) }
        (ks.getKey(KEY_ALIAS, null) as? SecretKey)?.let { return it }
        val spec = KeyGenParameterSpec.Builder(
            KEY_ALIAS, KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
        )
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            .setKeySize(256)
            .setRandomizedEncryptionRequired(true)
            .build()
        val kg = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, PROVIDER)
        kg.init(spec)
        return kg.generateKey()
    }
}
